config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  resources :static_pages, only: [:new, :show]
  resources :dailygoals, only: [:index,:new, :create, :show]
  resources :weeks, only: [:index, :new, :create, :show]
  resources :seasons, only: [:index, :new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/context.rb
class Context < ApplicationRecord
end

app/models/dailygoal.rb
class Dailygoal < ApplicationRecord
end

app/models/season.rb
class Season < ApplicationRecord
end

app/models/week.rb
class Week < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contexts_controller.rb
class ContextsController < ApplicationController

    def index
        @contexts = Context.all
    end

    def new
        @context = Context.new
    end

    def create
        @context = Context.create(context_params)
        redirect_to root_path
    end

    private

    def context_params
        params.require(:context).permit(:timeperiod, :first, :second, :third, :fourth, :fifth)
    end
end

app/controllers/dailygoals_controller.rb
class DailygoalsController < ApplicationController

    def index
        @dailygoals = Dailygoal.all
    end

        def new
        @dailygoal = Dailygoal.new
    end

    def create
        @dailygoal = Dailygoal.create(dailygoal_params)
        redirect_to root_path
    end

    private

    def dailygoal_params
        params.require(:dailygoal).permit(:date, :firstgoal, :secondgoal, :thirdgoal)
    end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController

    def index
        @seasons = Season.all
    end

        def new
        @season = Season.new
    end

    def create
        @season = Season.create(season_params)
        redirect_to root_path
    end

    private

    def season_params
        params.require(:season).permit(:season, :firstfocus, :secondfocus, :thirdfocus, :fourthfocus, :fifthfocus)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def index

    end
    
    def new
     
    end

    def show
  
    end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController

    def index
        @weeks = Week.all
    end

        def new
        @week = Week.new
    end

    def create
        @week = Week.create(week_params)
        redirect_to root_path
    end

    private

    def week_params
        params.require(:week).permit(:weekof, :firstproject, :secondproject, :thirdproject)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contexts_helper.rb
module ContextsHelper
end

app/helpers/dailygoals_helper.rb
module DailygoalsHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/contexts/index.html.erb
<br />
<br />
<div class="booyah-box text-center col-6 offset-3">
    <h2>What's Up? - Archive</h2>
    <br />
    <br />
    <% @contexts.each do |context| %>
  <div>
    <br />
    <h3><%= context.timeperiod %></h3><br />
    <p><%= context.first %></p><br />
    <p><%= context.second %></p><br />
    <p><%= context.third %></p><br />
    <p><%= context.fourth %></p><br />
    <p><%= context.fifth %></p><br />
<% end %>

    </div>


  <hr />
    

app/views/contexts/new.html.erb
<br />
<div class="booyah-box col-4 offset-4 text-center">
<h2>Add What’s Up Now</h2>
    <%= simple_form_for @context do |f| %>
        <%= f.input :timeperiod %>
        <%= f.input :first %>
        <%= f.input :second %>
        <%= f.input :third %>
        <%= f.input :fourth %>
        <%= f.input :fifth %>
        <br />
        <%= f.submit "Enter The List", class: 'btn btn-primary'%>
        <br />
    <% end %>
</div>
</div>

app/views/contexts/new:html.erb
<br />
<div class="booyah-box col-4 offset-4">

</div>

app/views/dailygoals/index.html.erb
<br />
<br />
<div class="booyah-box text-center col-6 offset-3">
    <h2>Daily Goals - Archive</h2>
    <br />
    <br />
    <% @dailygoals.each do |dailygoal| %>
  <div>
    <br />
    <h3><%= dailygoal.date %></h3><br />
    <p><%= dailygoal.firstgoal %></p><br />
    <p><%= dailygoal.secondgoal %></p><br />
    <p><%= dailygoal.thirdgoal %></p><br />
<% end %>

    </div>

  <hr />

app/views/dailygoals/new.html.erb
<br />
<div class="booyah-box col-4 offset-4 text-center">
    <h2>Add Goals for Today</h2>
    <%= simple_form_for @dailygoal do |f| %>
        <%= f.input :date %>
        <%= f.input :firstgoal %>
        <%= f.input :secondgoal %>
        <%= f.input :thirdgoal %>
        <br />
        <br />
        <%= f.submit "Enter Today's Goals", class: 'btn btn-primary'%>
        <br />
    <% end %>
</div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sunrise</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="http://vjs.zencdn.net/5.12.6/video-js.css" rel="stylesheet">
  </head>

  <body>
     <div id="flex-content-container">

          <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <%= link_to 'Sunrise', root_path, class: 'navbar-brand' %>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-md-0">
                <li>
                <%= link_to 'What\'s Up', new_season_path, class: 'btn btn-primary'%>                
                </li>
            </ul>
            <ul class="navbar-nav mr-auto mt-2 mt-md-0">
                <li>
                                <!-- Place to add Button to trigger This Week modal -->
                <%= link_to 'This Week', new_week_path, class: 'btn btn-primary'%>                
                </li>
            </ul>
            <ul class="navbar-nav mr-auto mt-2 mt-md-0">
                <li>
                <%= link_to 'Today', new_dailygoal_path, class: 'btn btn-primary'%>                
                </li>
            </ul>
            <ul class="navbar-nav mr-auto mt-2 mt-md-0">
              <li class="nav-item">
                <a class="nav-link" href="http://www.baynews9.com/content/news/baynews9/weather/klystron-9-radar.html">Weather</a>
              </li>
            </ul>
            <ul class="navbar-nav mr-auto mt-2 mt-md-0">
              <li class="nav-item">
                <a class="nav-link" href="https://unsplash.com">Beauty</a>
            </ul>
                        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
              <li class="nav-item">
                <a class="nav-link" href="https://splurty-kalen-hammann.herokuapp.com">Inspiration</a>
            </ul>
          </div>
        </nav>
     </div>
    <%= yield %>
    <script src="http://vjs.zencdn.net/5.12.6/video.js"></script>
    <script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
  </body>
</html>

app/views/seasons/index.html.erb
<br />
<br />

<div class="booyah-box text-center col-6 offset-3">
    <br />
    <br />
    <h2>What's Up? - Archive</h2>


    <% @seasons.each do |season| %>
    <div>
        <br />
        <h3><%= season.season %></h3><br />
        <p><%= season.firstfocus %></p><br />
        <p><%= season.secondfocus %></p><br />
        <p><%= season.thirdfocus %></p><br />
        <p><%= season.fourthfocus %></p><br />
        <p><%= season.fifthfocus %></p><br />
        <% end %>
    </div>
</div>

<hr />

app/views/seasons/new.html.erb
<br />
<div class="booyah-box col-4 offset-4">
<h2 class="text-center">Add This Season's Areas of Focus</h2>
    <%= simple_form_for @season do |f| %>
        <%= f.input :season %>
        <%= f.input :firstfocus %>
        <%= f.input :secondfocus %>
        <%= f.input :thirdfocus %>
        <%= f.input :fourthfocus %>
        <%= f.input :fifthfocus %>
        <br />
        <%= f.submit "Save", class: 'btn btn-primary'%>
        <br />
    <% end %>
</div>  

app/views/static_pages/index.html.erb
<html>
    <br />
    <div class="booyah-box col-10 offset-1 text-center">
        <br />
        <h1 class="text-center"> Good Morning, 
        <br />
        Kalen!</h1>
        


        <div class="row feature text-center">
            <div class="col-12 col-sm">
                <h3>What's Up?</h3>
                <p><%= Season.last.firstfocus %></p>
                <p><%= Season.last.secondfocus %></p>
                <p><%= Season.last.thirdfocus %></p>
                <p><%= Season.last.fourthfocus %></p> 
                <p><%= Season.last.fifthfocus %></p> 
                <br />                
                <%= link_to 'What\'s Up Archive', seasons_path, class: 'btn btn-primary'%> 
            </div>
            <div class="col-12 col-sm">
                <h3>Weekly Goals</h3>            
                <p><%= Week.last.firstproject %></p>
                <p><%= Week.last.secondproject %></p>
                <p><%= Week.last.thirdproject %></p>
                <br />
                <%= link_to 'Weekly Goals Archive', weeks_path, class: 'btn btn-primary'%> 
            </div>
            <div class="col-12 col-sm">
                <h3>Daily Goals</h3>
                <p><%= Dailygoal.last.firstgoal %></p>
                <p><%= Dailygoal.last.secondgoal %></p>
                <p><%= Dailygoal.last.thirdgoal %></p>
                <br />
                <%= link_to 'Daily Goals Archive', dailygoals_path, class: 'btn btn-primary'%> 
            </div>
            <br />
            <br />
            <br />
            <br />
        </div>
    </div> 

    <br />
    <div class="booyah-box col-10 offset-1 text-center">
        <h2 class="text-center"> Here's your TED fix: </h2>
        <br />

        <div class="col-8 offset-2 text-center">
            <iframe width="738" height="415.5" src="https://www.youtube.com/embed/esD6aaIjhek" frameborder="0" allowfullscreen></iframe>
        <br />
        (<a href="https://www.ted.com/talks">Complete list of TED talks</a>)
        (<a href="https://www.ted.com/surpriseme">TED talks "Surprise me!"</a>)
            </div>
        <br />
        <h2 class="text-center"> (Enjoy the day and Make It Count!)</h2>
        </div>
</html>

app/views/static_pages/wrap_code.html.erb
<% last_week = Week.last %>
<% if last_week %>
display lines
<% end %>

If anything could be nil, wrap it like this!

app/views/weeks/index.erb
<br />
<br />

<div class="booyah-box text-center col-6 offset-3">
    <br />
    <br />
    <h2>Weekly Goals Archive</h2>
    <% @weeks.each do |week| %>
  <div>
    <br />
    <h3><%= week.weekof %></h3><br />
    <p><%= week.firstproject %></p><br />
    <p><%= week.secondproject %></p><br />
    <p><%= week.thirdproject %></p><br />

    </div>


  <hr />
    <% end %>

</div>

app/views/weeks/new.html.erb
<br />
<div class="booyah-box col-4 offset-4 text-center">
    <h2>Add Goals for This Week</h2>
    <%= simple_form_for @week do |f| %>
        <%= f.input :weekof %>
        <%= f.input :firstproject %>
        <%= f.input :secondproject %>
        <%= f.input :thirdproject %>
        <br />
        <%= f.submit "Enter This Week's Goals", class: 'btn btn-primary'%>
        <br />
    <% end %>
</div>  

app/views/weeks/show.erb
<br />
<br />
<div class="booyah-box text-center col-10 offset-1">
    <h2>Weekly Goals Archive</h2>
    <br />
    <br />
    <% @weeks.each do |week| %>
  <div>
    <br />
    <h3><%= week.weekof %></h3><br />
    <p><%= week.firstproject %></p><br />
    <p><%= week.secondproject %></p><br />
    <p><%= week.thirdproject %></p><br />

    </div>


  <hr />
    <% end %>

</div>